### ISSUE TITLE
Minor code typo in readme file 'Intallation Instructions'

### ISSUE THREAD

**Issue by telefunkenvf14** [lshifr/CodeFormatter#5]
https://github.com/lshifr/CodeFormatter/blob/master/README.md#installation

I noticed that: `FileNameJoin[$UserBaseDirectory, "Applications"]` is missing `{ }` which causes errors. Replace with: `FileNameJoin[{$UserBaseDirectory, "Applications"}]`

**Comment by lshifr** [comment]
Thanks for noticing! Fixed now.
